import BreadcrumsCustom from "components/Common/Breadcrums"
import Head from "next/head"
import { useTranslation } from "react-i18next"
import FilterBar from "./section/filterBar/FilterBar"
import ListServices from "./section/ListServices/ListServices"

const ServicesPage = () => {
  const { t } = useTranslation(["base"])

  return (
    <>
      <>
        <Head>
          <title>Forum page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="mb-20 page-container page-container--child px-2 pt-16 md:pt-[72px] ">
          <div className="grid grid-cols-3 gap-4 mt-10 md:gap-7">
            <div className="col-span-3">
              <BreadcrumsCustom
                items={[
                  { label: t("base:pages.home"), href: "/" },
                  { label: t("base:pages.servies") }
                ]}
              />
            </div>
          </div>
          <div className="flex mt-10 gap-x-16">
            <div className="max-w-[290px] w-full">
              <FilterBar />
            </div>
            <div className="flex-1 ">
              <ListServices />
            </div>
          </div>
        </main>
      </>
    </>
  )
}

export default ServicesPage
