import Head from "next/head"
import Appoiment from "./appoiment/Appoiment"
import Banner from "./banner/Banner"

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="page-wrapper">
        <Banner />
        <div className="page-container">
          <Appoiment />
        </div>
      </main>
    </>
  )
}
