import Head from "next/head"

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Dashboard page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-20 page-wrapper pt-16 md:pt-[72px] overflow-hidden">
        <div className="space-y-10 md:space-y-16 page-container page-container--child">
          Test dashboard page
        </div>
      </main>
    </>
  )
}
