import ImageCustom from "components/Common/ImageCustom"
import UserSecondaryLayout from "layout/User/UserSecondaryLayout"
import { useEffect, useState } from "react"
import { useTranslation } from "react-i18next"
import { IBreadcrum } from "types/Base.type"
import { IconButton, InputAdornment, OutlinedInput } from "@mui/material"
import { IconSearch } from "../Home/section/banner/Search"
import { useRouter } from "next/router"
import ResultsSearch from "./sections/results"
import ChipCustom from "components/Common/Chip/Chip"
import Head from "next/head"

const SearchPage = () => {
  const { t } = useTranslation(["home", "base"])
  const router = useRouter()

  const [searchValue, setSearchValue] = useState("")
  const breadrums: IBreadcrum[] = [
    { label: t("base:pages.home"), href: "/" },
    { label: t("base:pages.search") }
  ]
  useEffect(() => {
    if (router.query.keyword) {
      setSearchValue(router.query.keyword?.toString())
    }
  }, [router.query])
  return (
    <>
      <Head>
        <title>Search page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserSecondaryLayout breadrums={breadrums}>
        <div className="flex flex-col items-center mx-auto bg-white w-full">
          <div className="relative w-[560px] h-[250px]">
            <ImageCustom
              src={"/images/search-image.webp"}
              alt="search-image"
              fill
              className="object-cover"
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
            />
          </div>
          <h1 className="py-3 text-2xl font-semibold text-h1">
            Tra cứu nhanh thông tin sức khỏe
          </h1>
          <div className="flex items-center justify-between h-11 md:h-[64px] w-full max-w-[652px]">
            <OutlinedInput
              onChange={(e) => setSearchValue(e.target.value)}
              placeholder={t("banner.search.placeholder")}
              className="h-full bg-[#FAFBFE] text-xs md:text-base rounded-none rounded-tl-lg rounded-bl-lg border-r-0 border-none outline-none"
              fullWidth
              value={searchValue}
              startAdornment={
                <InputAdornment position="start">
                  <IconSearch />
                </InputAdornment>
              }
            />
            <IconButton
              aria-label="delete"
              className="text-white h-full w-14 md:w-[72px] flex items-center justify-center rounded-none rounded-tr-lg rounded-br-lg bg-primary hover:bg-primary"
            >
              <IconSearch />
            </IconButton>
          </div>
          <div className="flex flex-col items-center mt-4 space-y-3 max-w-[500px]">
            <h3>Từ khóa được tìm kiếm nhiều nhất:</h3>
            <ul className="flex flex-wrap items-center justify-center w-full gap-4 list-none">
              {new Array(7).fill(null).map((item, index) => (
                <li key={index}>
                  <ChipCustom label="Covid-19" />
                </li>
              ))}
            </ul>
          </div>
        </div>
        <div className="flex flex-col gap-y-4">
          {/* <ResultsSearch servicePackages={ } blogs={ } posts={ } /> */}
        </div>
      </UserSecondaryLayout>
    </>
  )
}

export default SearchPage
