import UserLayout from 'layout/User/UserLayout';
import Head from 'next/head';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=""></main>
    </>
  );
};
Home.getLayout = (page) => {
  return <UserLayout>{page}</UserLayout>;
};
export default Home;
