import UserSecondaryLayout from "layout/User/UserSecondaryLayout"
import Head from "next/head"
import { useTranslation } from "react-i18next"
import { IBreadcrum } from "types/Base.type"
import SiderBar from "./section/siderbar"

const ProfilePage = () => {
  const { t } = useTranslation(["base"])
  const breadrums: IBreadcrum[] = [
    { label: t("base:pages.home"), href: "/" },
    { label: t("base:pages.profile") }
  ]
  return (
    <>
      <Head>
        <title>Profile page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <UserSecondaryLayout breadrums={breadrums}>
        <div className="w-full mt-10">
          <SiderBar />
        </div>
      </UserSecondaryLayout>
    </>
  )
}

export default ProfilePage
