import Head from "next/head"
import React from "react"
import TableQuestion from "./section/TableQuestion"

const QuestionsPage = () => {
  return (
    <>
      <Head>
        <title>Question page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main>
        <div className="p-8">
          <TableQuestion />
        </div>
      </main>
    </>
  )
}

export default QuestionsPage
