import UserSecondaryLayout from "layout/User/UserSecondaryLayout"
import Head from "next/head"
import { useTranslation } from "react-i18next"
import { IBreadcrum } from "types/Base.type"
import CreateQuestion from "./section/create"
import DetailForum from "./section/detail"
const DetailPage = () => {
  const { t } = useTranslation(["base", "forum"])
  const breadrums: IBreadcrum[] = [
    { label: t("base:pages.home"), href: "/" },
    { label: t("base:pages.forum"), href: "/forum" },
    { label: t("base:pages.detail") }
  ]

  return (
    <>
      <Head>
        <title>Forum page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserSecondaryLayout breadrums={breadrums}>
        <div className="grid grid-cols-3 gap-4 mt-10 md:gap-7">
          <div className="order-last col-span-3 space-y-4 md:order-first md:col-span-2">
            <DetailForum />
          </div>
          <div className="col-span-3 md:col-span-1">
            <CreateQuestion />
          </div>
        </div>
      </UserSecondaryLayout>
    </>
  )
}

export default DetailPage
