import { Pagination } from "@mui/material"
import BreadcrumsCustom from "components/Common/Breadcrums"
import Head from "next/head"
import { useTranslation } from "react-i18next"
import CardForum from "../components/CardForum"
import CreateQuestion from "./section/create"
import Search from "./section/search"

const ForumPage = () => {
  const { t } = useTranslation(["base", "forum"])

  return (
    <>
      <Head>
        <title>Forum page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-20 page-container page-container--child px-2 pt-16 md:pt-[72px] ">
        <div className="grid grid-cols-3 gap-4 mt-10 md:gap-7">
          <div className="col-span-3">
            <BreadcrumsCustom
              items={[
                { label: t("base:pages.home"), href: "/" },
                { label: t("base:pages.forum") }
              ]}
            />
          </div>
          <div className="grid grid-cols-3 col-span-3 gap-7">
            <div className="order-last col-span-3 md:order-first md:col-span-2">
              <CreateQuestion />
            </div>
            <div className="col-span-3 md:col-span-1">
              <Search />
            </div>
          </div>
          <div className="w-full col-span-3 md:col-span-2 background-primary">
            <CardForum kind="large" />
            <div className="flex flex-col mt-6 space-y-3">
              <div className="flex items-center space-x-2 text-xl">
                <span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="currentColor"
                    className="w-6 h-6 stroke-red-500"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
                    />
                  </svg>
                </span>
                <span> {t("forum:questionHeadingFav")}</span>
              </div>
              <div className="grid grid-cols-1 gap-y-4 md:gap-x-6 md:grid-cols-3">
                <CardForum />
                <CardForum />
                <CardForum />
              </div>
            </div>
          </div>
          <div className="w-full col-span-3 space-y-4 md:col-span-2 background-primary">
            <h4 className="text-xl "> {t("forum:allquestion")}</h4>
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
              <CardForum />
              <CardForum />
              <CardForum />
              <CardForum />
              <CardForum />
              <CardForum />
            </div>
            <Pagination
              count={10}
              color="primary"
              className="pt-6 md:ml-auto md:w-fit"
              shape="rounded"
            />
          </div>
        </div>
      </main>
    </>
  )
}

export default ForumPage
