import Head from "next/head"
import React from "react"
import TableQuestionRequest from "./section/TableQuestionRequest"

const QuestionRequest = () => {
  return (
    <>
      <Head>
        <title>Question request page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main>
        <div className="p-8">
          <TableQuestionRequest />
        </div>
      </main>
    </>
  )
}

export default QuestionRequest
